[project]
name = "cms1500"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypdf>=6.0.0",
    "faker>=28.0.0",
    "pdf2image>=1.17.0"
]

[project.optional-dependencies]
test = [
    "pytest>=8.0.0"
]
